knp_paginator:
    page_range: 5
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
